- name: variables from files
  hosts: localhost
  become: yes
  vars:
    vars.yml
  task:
    - name: print information
      ansible.builtin.debug:
        msg: "Hi, Welcome to {{course}} from {{trainer}} and duration is {{duration}}. {{wishes}}! "