- name: filters
  hosts: localhost
  become: yes

  tasks:
    - name: print default value
      ansible.builtin.debug:
        msg: "Hello {{course | default('Ansible') }}"

    - name: to uppercase
      hosts: localhost
      vars:
        greeting: "Hello, Good Morning"
      tasks:
        - name: converting into uppercase
          ansible.builtin.debug:
           msg: "{{ greeting | upper }}"

